name: Guardian CI
on: [push]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          pushd interfaces
          npm install
          npm run build
          popd
          pushd common
          npm install
          npm run build
          popd
          pushd logger-service
          npm install
          npm run build
          popd
          pushd frontend
          npm install
          npm run build
          popd
          pushd auth-service
          npm install
          npm run build
          popd
          pushd guardian-service
          npm install
          npm run build
          popd
          pushd api-gateway
          npm install
          npm run build
          popd
        env:
          CI: true
      - name: Test
        run: |
          pushd guardian-service
          npm run test
          popd
        env:
          CI: true
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test_results/**/*.xml
